### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by KyryloKilin** [soundxyz/docs#107]
A broken link on the page: https://docs.sound.xyz/protocol/overview/design#metadata-modules
![image](https://github.com/user-attachments/assets/d1c83c16-c856-42a6-a5e2-af9db4d0cadd)

A broken link on the page: https://docs.sound.xyz/protocol/core/sound-edition
![image](https://github.com/user-attachments/assets/29e84fee-2aea-4420-99bf-228431bdbd94)

A  broken link on the page: https://docs.sound.xyz/protocol/libraries/erc721a-queryable-upgradeable
![image](https://github.com/user-attachments/assets/7bb0a5b2-11cc-4cba-b0ba-5465d85825d1)

**Comment by saihaj** [comment]
should be fixed by https://github.com/soundxyz/docs/pull/108
